adding integration framework
onosproject/wcmp-app pull request #15
Opened 2022-07-20 18:38 UTC by eesha-deepak

2022-07-20 19:10 UTC, adibrastegarnia commented
retest this please

2022-07-20 19:51 UTC, adibrastegarnia commented
retest this please

2022-07-21 15:57 UTC, adibrastegarnia requested changes

2022-07-21 15:57 UTC, adibrastegarnia commented on test/p4rt/suite.go
> +// TestSuite is the onos-config GNMI test suite
Update comment no gnmi or onos-config in the comments

2022-07-21 15:57 UTC, adibrastegarnia commented on test/p4rt/suite.go
> +		return int64(i)
we can remove getInt function since there is no use of it now.

2022-07-21 15:57 UTC, adibrastegarnia commented on test/p4rt/suite.go
> +// SetupTestSuite sets up the onos-config GNMI test suite
Same thing about comment here

2022-07-21 15:58 UTC, adibrastegarnia commented on test/p4rt/testP4RTConnectivity.go
> +func (s *TestSuite) testSinglePath(t *testing.T) {
Rename the test to TestP4RTConnectivity  and we add logic later

2022-07-21 16:21 UTC, adibrastegarnia commented
retest this please

2022-07-21 18:11 UTC, ray-milkey commented
retest this please

2022-07-21 18:36 UTC, adibrastegarnia commented
retest this please

2022-07-21 18:58 UTC, adibrastegarnia commented
retest this please

2022-07-21 20:46 UTC, adibrastegarnia commented
retest this please

2022-07-21 20:49 UTC, eesha-deepak commented
retest this please

2022-07-21 21:15 UTC, adibrastegarnia approved these changes

2022-07-21 21:16 UTC, merged